# Generated by Django 2.2.6 on 2019-10-24 04:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Заметка', 'verbose_name_plural': 'Заметки'},
        ),
        migrations.RemoveField(
            model_name='note',
            name='Text',
        ),
        migrations.RemoveField(
            model_name='note',
            name='User',
        ),
        migrations.AddField(
            model_name='note',
            name='text',
            field=models.TextField(default=django.utils.timezone.now, max_length=255, verbose_name='Заметка'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
