# Generated by Django 2.2.6 on 2019-10-24 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20191024_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='CategoryName', max_length=30, verbose_name='Логин')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='NoteTitle', max_length=30, verbose_name='Титул'),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(default='NoteText', verbose_name='Заметка'),
        ),
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='notes.Category'),
            preserve_default=False,
        ),
    ]
