# Generated by Django 2.2.6 on 2019-10-24 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20191024_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default=None, max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='notes.Category'),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(default=None, verbose_name='Заметка'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default=None, max_length=30, verbose_name='Титул'),
        ),
    ]
